collision_spheres:
  base_link:
    - center: [0.0005, 5.3e-05, 0.060019]
      radius: 0.044021
  gripper_Left_1_Link:
    - center: [0.0, 0.0, 0.05]
      radius: 0.05
  gripper_Left_2_Link:
    - center: [0.0, 0.0, 0.05]
      radius: 0.05
  gripper_Left_Support_Link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05
  gripper_Right_1_Link:
    - center: [0.0, 0.0, 0.05]
      radius: 0.05
  gripper_Right_2_Link:
    - center: [0.0, 0.0, 0.05]
      radius: 0.05
  gripper_Right_Support_Link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05
  gripper_base_link:
    - center: [0.0, 0.0, 0.0]
      radius: 0.040825
  left_pad:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05
  link_1:
    - center: [0.0, 0.0, 0.0]
      radius: 0.129099
  link_2:
    - center: [0.0, 0.0, 0.0]
      radius: 0.129099
  link_3:
    - center: [0.0, 0.0, 0.0]
      radius: 0.122474
  link_4:
    - center: [0.0, 0.0, 0.0]
      radius: 0.125
  link_5:
    - center: [0.0, 0.0, 0.0]
      radius: 0.129099
  link_6:
    - center: [0.0, 0.0, 0.0]
      radius: 0.129099
  link_7:
    - center: [0.001094, -7.7e-05, -0.010119]
      radius: 0.033564
  right_pad:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05
